#use_frameworks!

source 'https://github.com/RichieZhl/Spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.4'

target 'react-native-svg_Example' do
  pod 'react-native-svg', :path => '../'

  target 'react-native-svg_Tests' do
    inherit! :search_paths

    
  end
  
  post_install do |installer|
      if defined? installer.pods_project
        installer.pods_project.targets.each do |target|
            if target.name == 'React'
              target.build_configurations.each do |config|
                  config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
              end
            end
            
            if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
              target.build_configurations.each do |config|
                  config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
              end
            end
        end
      end
    end
end
